# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01home():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_01home(self):
    self.driver.get("https://www.toolsvilla.com/category/farm/special-farm-tools/")
    self.driver.set_window_size(1382, 736)
    time.sleep(20)
    elements = self.driver.find_elements(By.ID, "fixed-nav")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "schText").click()
    element = self.driver.find_element(By.ID, "schText")
    assert element.is_enabled() is True
    self.driver.find_element(By.CSS_SELECTOR, ".relative img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-backdrop").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-backdrop").click()
    self.driver.execute_script("window.scrollTo(0,1682)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".middle-section")
    assert len(elements) > 0
  
